name: CI
on: [push]
jobs:
  eslint:
    name: Lint Code Base
    runs-on: windows-2016

    steps:
      - run: node -v
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Run EsLint
        run: npm run lint

      - name: Run test
        run: npm run ci:test
