name: CI
on: [push]
jobs:
  standard-checks:
    name: Lint & test Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install packages
        run: npm ci

      - name: Run EsLint
        run: npm run lint

      - name: Run test
        run: npm run ci:test
